const config = {
    home: '*',
    search: '/search',
    detail: '/products/:id',
    cart: '/cart',
    checkout: '/checkout',
    shops: '/all-shops',
    shop: '/shop/:id',
    sale: '/sale-page',
    topcate: '/top-category',
    toprate: '/top-rating',
    featurebrand: '/feature-brand',
    newarrival: '/new-arrival',
    bigdiscount: '/big-discount',
    user: '/user/*',
    signup: '/signup',
    login: '/login',
    resetpass: '/reset-password',
    catetabletmobile: '/cate-nav',
    dashboard: '/admin/dashboard',
    products: '/admin/products',
    categories: '/admin/categories',
    brands: '/admin/brands',
    orders: '/admin/orders',
    customers: '/admin/customers',
};

export default config;
